# Generated by Django 4.1.6 on 2023-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="ConfirmPassword",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
