# Generated by Django 4.1.6 on 2023-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0002_newuser_confirmpassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("subject", models.TextField(max_length=1500)),
            ],
        ),
    ]
